mode: "exact"
theme: "modern"
language: "<%= I18n.locale.to_s.split('-')[0].downcase %>"
skin: "lightgray"
schema: "html5-strict"
element_format: "html"
resize: true
browser_spellcheck: true
plugins:
  - layer
  - table
  - insertdatetime
  - preview
  - searchreplace
  - contextmenu
  - paste
  - directionality
  - fullscreen
  - noneditable
  - visualchars
  - nonbreaking
  - textcolor
  - colorpicker

# Each line is a toolbar
toolbar:
  - styleselect formatselect fontselect fontsizeselect | forecolor backcolor
  - cut copy paste pastetext pasteword | search replace | undo redo | link unlink anchor image cleanup code | insertdate inserttime preview | bold italic underline strikethrough | justifyleft justifycenter justifyright justifyfull | sub sup | bullist numlist | outdent indent blockquote | tablecontrols | hr removeformat visualaid
